name: Zones
main: com.zones.Zones
version: 2.2
authors: [ 'Meaglin' , 'Mysteryman' ]
website: https://github.com/Meaglin/0xFFFF
description: The Over optimized Area Protection tool with integrated Anti Grief options.
commands:
     