name: Zones
main: com.zones.Zones
version: 2.0b27
author: Meaglin
website: https://github.com/Meaglin/0xFFFF
description: The Over optimized Area Protection tool with integrated Anti Grief options.
database: true
commands:
    zhelp:
        aliases: ["z?"]
        description: info command for all Zones commands.
        usage: /<command> <command name>
    zcreate:
        description: see /zhelp
        usage: /<command> 
    zset:
        description: see /zhelp
        usage: /<command> 
    zadd:
        aliases: [za,"z+"]
        description: see /zhelp
        usage: /<command> 
    zremove:
        aliases: [zrem, zdel, "z-"]
        description: see /zhelp
        usage: /<command> 
    zsetplot:
        description: see /zhelp
        usage: /<command> 
    zsetheight:
        aliases: [zsh]
        description: see /zhelp
        usage: /<command> 
    zimport:
        aliases: [zi]
        description: see /zhelp
        usage: /<command> 
    zsetdepth:
        aliases: [zsd]
        description: see /zhelp
        usage: /<command> 
    zsave:
        aliases: [zsv]
        description: see /zhelp
        usage: /<command> 
    zconfirm:
        aliases: [zcon]
        description: see /zhelp
        usage: /<command> 
    zsetz:
        aliases: [zsz]
        description: see /zhelp
        usage: /<command> 
    zstop:
        aliases: [zst]
        description: see /zhelp
        usage: /<command> 
    zsetuser:
        aliases: [zsu, zsuser, zaddmember, zam, "zu+", "zuser+"]
        description: see /zhelp
        usage: /<command> 
    zsetgroup:
        aliases: [zsg, "zg+", "zgroup+"]
        description: see /zhelp
        usage: /<command> 
    zaddadmin:
        aliases: [zaa, zaddowner, "za+"]
        description: see /zhelp
        usage: /<command> 
    zremoveadmin:
        aliases: [zra, zremadmin, zdeladmin, "za-"]
        description: see /zhelp
        usage: /<command> 
    zselect:
        aliases: [zs, zsel]
        description: see /zhelp
        usage: /<command> 
    zsettype:
        description: see /zhelp
        usage: /<command> 
    zregioninfo:
        description: see /zhelp
        usage: /<command> 
    zgetaccess:
        aliases: [zga, zrights]
        description: see /zhelp
        usage: /<command> 
    zdelete:
        aliases: [zdel]
        description: see /zhelp
        usage: /<command> 
    zsetname:
        aliases: [zsn]
        description: see /zhelp
        usage: /<command> 
    ztogglehealth:
        aliases: [zth, zthp]
        description: see /zhelp
        usage: /<command> 
    ztoggledynamite:
        aliases: [ztnt, ztd]
        description: see /zhelp
        usage: /<command> 
    ztogglelava:
        aliases: [ztl]
        description: see /zhelp
        usage: /<command> 
    ztogglewater:
        aliases: [ztw]
        description: see /zhelp
        usage: /<command> 
    ztogglemobs:
        aliases: [ztm]
        description: see /zhelp
        usage: /<command> 
    ztoggleanimals:
        aliases: [zta]
        description: see /zhelp
        usage: /<command> 
    zedit:
        description: see /zhelp
        usage: /<command> 
    zmerge:
        description: see /zhelp
        usage: /<command> 
    zreload:
        description: see /zhelp
        usage: /<command> 
    ztoggle:
        aliases: [zt]
        description: see /zhelp
        usage: /<command> 
    zinfo:
        description: see /zhelp
        usage: /<command>   
    zaccess:
        description: see /zhelp
        usage: /<command>   
    zsetclass:
        description: see /zhelp
        usage: /<command>   
    zdefine:
        aliases: [zd]
        description: see /zhelp
        usage: /<command>   
    zredefine:
        aliases: [zrd]
        description: see /zhelp
        usage: /<command>   
    zexport:
        aliases: [zexp , zex]
        description: see /zhelp
        usage: /<command>  
    zabout:
        aliases: []
        description: see /zhelp
        usage: /<command>  
    zwho:
        aliases: [zplayerlist]
        description: see /zhelp
        usage: /<command>  
    z:
        aliases: [zone]
        description: see /zhelp
        usage: /<command>  
    zclaim:
        aliases: []
        description: see /zhelp
        usage: /<command>  
    ungod:
        aliases: []
        description: see /zhelp
        usage: /<command>  
    god:
        aliases: []
        description: see /zhelp
        usage: /<command>  